### ISSUE TITLE
Moderate vulnerabilities , need upgrade axios

### ISSUE THREAD

**Issue by adrienbecuwe** [arvind-agarwal/node_extra_ca_certs_mozilla_bundle#6]
Hi , if you do a simple npm audit you can see you have 1 moderate vulnerabilities 

"Moderate  - Axios Cross-Site Request Forgery Vulnerability   , https://github.com/advisories/GHSA-wf5p-g6vw-rhxx "

Juste need to upgrade axios to 1.6.5.

I try to push a branch with the fix but i dont have the right to do it

Thanks
Adrien

**Comment by arvind-agarwal** [comment]
I have released a new version with updated packages. Thanks.
